# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- master
- 202???
- 201???

trigger:
  batch: true
  branches:
    include:
    - master
    - 202???
    - 201???

# this part need to be set in UI
schedules:
- cron: "0 0 * * 6"
  displayName: Weekly build
  branches:
    include:
    - master
    - 202???
    - 201???
  always: true

resources:
  repositories:
  - repository: sonic-swss
    type: github
    name: sonic-net/sonic-swss
    endpoint: sonic-net

parameters:
  - name: debian_version
    type: string
    default: buster
variables:
  - name: BUILD_BRANCH
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      value: $(System.PullRequest.TargetBranch)
    ${{ else }}:
      value: $(Build.SourceBranchName)

stages:
- stage: Build

  jobs:
  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: amd64
      sonic_slave: sonic-slave-${{ parameters.debian_version }}
      swss_common_artifact_name: sonic-swss-common
      artifact_name: sonic-sairedis
      syslog_artifact_name: sonic-sairedis.syslog
      run_unit_test: true
      archive_gcov: true
      debian_version: ${{ parameters.debian_version }}
